<a href="https://colab.research.google.com/github/Nerofinn/Linear-Algebra-Lab-Rep-1-2021/blob/main/Assignment6_ORLAIN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Algebra for ECE

Laboratory 6: Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more. 

## Objectives

At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [5]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for matrix **A** its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$


This can now be achieved programmatically by using np.transpose() oor using the T method.

In [6]:
A= np.array([
    [1, 2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [7]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [8]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [9]:
np.array_equiv(AT1, AT2)

True

In [11]:
B = np.array([
    [1, 2, 3, 4],
    [1, 0, 2, 1],
])
B.shape

(2, 4)

In [12]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T. shape

(4, 2)

## Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
A=np.array([
    [2, 4, 6],
    [1, 2, 3],
    [0, 1, 2],
    [9, 8, 7]        
])
A.shape


(4, 3)

In [ ]:
np.transpose(A).shape


(3, 4)

In [ ]:
A.T.shape

(3, 4)

## Dot Product/ Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices ***X*** and ***Y***:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to ***X*** and ***Y***:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

This could be achieved programmatically using np.dot (), np.matmul() or the @operator.






In [ ]:
A = np.array([
    [1, 2],
    [0, 1],
])
J = np.array([
    [-1, 0],
    [2, 2],
])

In [ ]:
np.dot(A,J)

array([[3, 4],
       [2, 2]])

In [ ]:
A.dot(J)

array([[3, 4],
       [2, 2]])

In [ ]:
A @ J

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(A,J)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

## Rule 1: The inner dimensions of the two matrices in question must be the same.

So given a matrix **A** with a shape of (a,b) where a and b are any integers. If we want to do a dot product between ***A*** and another matrix ***B***, then matrix ***B*** should have a shape of (b,c) where b and c are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case **A** has a (3,2), B has a shape of (3,2,) and C has a shape of (2,3). So  the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
    [2, 3],
    [1, 2],
    [0, 2]
])
J = np.array([
    [1, 2, 3],
    [0, 2, 4]
])
O = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A.shape)
print(J.shape)
print(O.shape)

(3, 2)
(2, 3)
(3, 2)


In [ ]:
A @ J

array([[ 2, 10, 18],
       [ 1,  6, 11],
       [ 0,  4,  8]])

In [ ]:
J @ O

array([[22, 28],
       [26, 32]])

In [ ]:
X = np.array([
    [1, 2, 3, 0]
])
Y = np.array([
    [1, 0, -4, 1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T @ X

array([[  1,   2,   3,   0],
       [  0,   0,   0,   0],
       [ -4,  -8, -12,   0],
       [  1,   2,   3,   0]])

In [ ]:
X @ Y.T

array([[-11]])

## Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
1. $A \cdot B \neq B \cdot A$
2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A +C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$


In [ ]:
A = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
])
B = np.array([
    [1, 2, 3],
    [0, 1, 2],
    [1, 3, 5]
])
C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

(3, 3)
(3, 3)
(3, 3)


In [ ]:
np.array_equiv(A@B, B@A)

False

In [ ]:
E = A @ (B @ C)
E

array([[210, 249, 288],
       [420, 498, 576],
       [630, 747, 864]])

In [ ]:
F = (A@B) @ C
F

array([[210, 249, 288],
       [420, 498, 576],
       [630, 747, 864]])

In [ ]:
np.array_equiv(E,F)

True

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(np.eye(3))

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
B = np.array([
    [1, 5, 2],
    [3, -1, -1],
    [0, -2, 1]
])
np.linalg.det(B)

-30.000000000000014

In [ ]:
## Now other mathematics classes would require you asdasdasd





B = np.array([
    [1, 3, 5, 6],
    [0, 3, 1, 3],
    [3, 1, 8, 2],
    [5, 2, 6, 8]
])
np.linalg.det(B)

-235.0000000000002

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [1, 7],
    [-3, 5]
])
np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
    [6, 9, 0],
    [4, 2, -1],
    [5, 6, 7]
])
Q= np.linalg.inv(P)
Q

array([[-0.11299435,  0.3559322 ,  0.05084746],
       [ 0.18644068, -0.23728814, -0.03389831],
       [-0.07909605, -0.05084746,  0.13559322]])

In [ ]:
np.array(P @ Q, dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

## Activity

## Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than  (3,3) . In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [17]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
F = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
])
I = np.array([
    [1, 2, 3],
    [3, 6, 9],
    [1, 3, 5]
])
N = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

1.$A \cdot B \neq B \cdot A$

In [20]:
np.dot(F,I)

array([[ 10,  23,  36],
       [ 20,  46,  72],
       [ 30,  69, 108]])

In [21]:
np.dot(I,F)

array([[ 14,  28,  42],
       [ 42,  84, 126],
       [ 22,  44,  66]])

2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [29]:
M=np.dot(I,N)
O=np.dot(F,I)
P=np.dot(F,M)
Q=np.dot(O,N)

In [32]:
print(P)

[[ 1640  3772  5904]
 [ 3280  7544 11808]
 [ 4920 11316 17712]]


In [33]:
print(Q)

[[ 1640  3772  5904]
 [ 3280  7544 11808]
 [ 4920 11316 17712]]


3. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [34]:
D= I+N
print(D)

[[ 11  25  39]
 [ 23  52  81]
 [ 31  72 113]]


In [35]:
np.dot(F,D)

array([[ 150,  345,  540],
       [ 300,  690, 1080],
       [ 450, 1035, 1620]])

In [38]:
E=np.dot(F,I)
print(E)

[[ 10  23  36]
 [ 20  46  72]
 [ 30  69 108]]


In [41]:
F=np.dot(F,N)
print(F)

[[ 22960  52808  82656]
 [ 45920 105616 165312]
 [ 68880 158424 247968]]


In [42]:
E+F

array([[ 22970,  52831,  82692],
       [ 45940, 105662, 165384],
       [ 68910, 158493, 248076]])

4. $(B+C)\cdot A = B\cdot A +C\cdot A$

In [43]:
np.dot((I,N),F)

array([[[  321440,   739312,  1157184],
        [  964320,  2217936,  3471552],
        [  505120,  1161776,  1818432]],

       [[ 3765440,  8660512, 13555584],
        [ 7530880, 17321024, 27111168],
        [11296320, 25981536, 40666752]]])

In [44]:
G=np.dot(I,F)
H=np.dot(N,F)

In [45]:
G + H

array([[ 4086880,  9399824, 14712768],
       [ 8495200, 19538960, 30582720],
       [11801440, 27143312, 42485184]])

5. $A\cdot I = A$

In [46]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
print(F)

[[ 22960  52808  82656]
 [ 45920 105616 165312]
 [ 68880 158424 247968]]


In [48]:
np.dot(F,I)

array([[ 22960.,  52808.,  82656.],
       [ 45920., 105616., 165312.],
       [ 68880., 158424., 247968.]])

6. $A\cdot \emptyset = \emptyset$

In [49]:
z_mat=np.zeros(F.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
F_dot_z=F.dot(np.zeros(F.shape))
F_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.array_equal(F_dot_z,z_mat)

True

In [54]:
null_mat=np.empty(F.shape,dtype=float)
null=np.array(null_mat,dtype=float)
print(null)
np.allclose(F_dot_z,null)

[[ 22960.  52808.  82656.]
 [ 45920. 105616. 165312.]
 [ 68880. 158424. 247968.]]


False